### PR TITLE
Update CdpEngine Benches

### PR DESCRIPTION
**Pull request by ferrell-code**
`liquidate_by_dex` benchmark is updated to correctly use worst case scenario. The `liquidate_by_auction` is also updated for worse case scenario, but there is no way to cheaply  know the path the function will take, so we will continue to just use the heavier weight of the two for which is `liquidate_by_auction`

### CODE REVIEW

**Comment by xlc** [comment]
Given the worse case scenario is significantly worse than the average scenario, we need to refund the extra weights so we can pack more liquidation transaction in a single block

**Comment by ferrell-code** [comment]
move to #1609

**Pull request closed without merging**
