### PR TITLE
EVM rpc return proper error if api doesn't exists at block_id

### LINKED ISSUE #2130: make EVM RPC handle error
Should handle data queries where the specified block hash does not exist
```
curl --location --request GET 'https://tc7-eth.aca-dev.network' \
--header 'Content-Type: application/json' \
--data-raw '{
    "id": 16,
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
        "from": "0x22293227a254a481883ca5e823023633308cb9ca",
        "to": "0x0000000000000000000000000000000000000806",
        "data": "0x0232027e65766d3a75e480db528101a381ce68544611c169ad7eb3420000000000000000",
        "value": "0x0",
        "gas": "0x2dc6c0"
      },
      "0x0"
    ]
}'|jq
```

```
{
  "id": 16,
  "jsonrpc": "2.0",
  "error": {
    "code": 6969,
    "message": "Error: -32603: runtime error: Application(Execution(AbortedDueToTrap(MessageWithBacktrace { message: \"wasm trap: wasm `unreachable` instruction executed\", backtrace: Some(Backtrace { backtrace_string: \"\\n    0: 0x764f - <unknown>!rust_begin_unwind\\n    1: 0x6fa8 - <unknown>!core::panicking::panic_fmt::h8f11323637b4db3b\\n    2: 0x4235d6 - <unknown>!EVMRuntimeRPCApi_call\\n\" }) })))"
  }
}
```

### PR DESCRIPTION
**Pull request by ermalkaleci**
Closes #2130

### CODE REVIEW

**Comment by zjb0807** [comment]
```
geth --gcmode archive --http
```
```
curl --location --request POST 'http://localhost:8545' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_call",
    "params": [
        {
            "from": "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1",
            "to": "0x478defc2fc2be13a505dafbdf1e5400847e2eff6",
            "data": "0x70a082310000000000000000000000002804f43ddd8c08b66b61a1cf8dcc744f1b109971",
            "value": "0x0",
            "gas": "0x2dc6c0"
        },
        "0x0"
    ],
    "id": 1
}'
{"jsonrpc":"2.0","id":1,"result":"0x"}
```
geth returns 0x, I think we should return 0x too

**Comment by ermalkaleci** [comment]
> ```
> geth --gcmode archive --http
> ```
> 
> 
>      
>   
> 
> ```
> curl --location --request POST 'http://localhost:8545' \
> --header 'Content-Type: application/json' \
> --data-raw '{
>     "jsonrpc": "2.0",
>     "method": "eth_call",
>     "params": [
>         {
>             "from": "0x90f8bf6a479f320ead074411a4b0e7944ea8c9c1",
>             "to": "0x478defc2fc2be13a505dafbdf1e5400847e2eff6",
>             "data": "0x70a082310000000000000000000000002804f43ddd8c08b66b61a1cf8dcc744f1b109971",
>             "value": "0x0",
>             "gas": "0x2dc6c0"
>         },
>         "0x0"
>     ],
>     "id": 1
> }'
> {"jsonrpc":"2.0","id":1,"result":"0x"}
> ```
> 
> 
>      
>   
> 
> geth returns 0x, I think we should return 0x too

this might be the response when contract doesn't exists. it our case is EVM doesn't exists

**Comment by ermalkaleci** [comment]
@zjb0807 I think this needs to be handled by eth_rpc_adapter

**Review by xlc — APPROVED** [review]
we should do eth rpc compatibility on eth rpc adapter layer.

do we need to have a different error code otherwise eth rpc adapter will need to do regex matching, which is fine.

**Comment by zjb0807** [comment]
https://github.com/paritytech/jsonrpc/blob/0a2702595b8831a9a30dec7dc476157c648c361c/core/src/types/error.rs#L28-L35
We can use the `ErrorCode::ServerError(code) => code` to do eth rpc compatibility on eth rpc adapter

**Pull request merged**
