### PR TITLE
Add stable asset

### PR DESCRIPTION
**Pull request by zjb0807**
https://github.com/AcalaNetwork/predeploy-contracts/pull/98

```
stdout: '$ truffle compile\n' +
    '\n' +
    'Compiling your contracts...\n' +
    '===========================\n' +
    '> Compiling ./contracts/utils/Address.sol\n' +
    '\n' +
    "ParserError: Expected identifier but got 'ILLEGAL'\n" +
    '  --> project:/contracts/utils/Address.sol:24:26:\n' +
    '   |\n' +
    '24 | \taddress public constant 3USD = 0x0000000000000000000300000000000000000001;\n' +
    '   | \t                        ^\n' +
    '\n' +
    '\x1B[31mCompilation failed. See above.\x1B[39m\n' +
    'Truffle v5.5.10 (core: 5.5.10)\n' +
    'Node v14.16.0\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.\n',
  stderr: 'error Command failed with exit code 1.\n'
```
Rename 3USD to t3USD in solidity and js package.

### CODE REVIEW

**Comment by zjb0807** [comment]
Deploy and publish the `taiKSM` and `3USD` on karura mainnet.
"taiKSM", "0x0000000000000000000300000000000000000000"
"3USD", "0x0000000000000000000300000000000000000001",

**Comment by zjb0807** [comment]
Maybe `TAI_KSM` `TAI_DOT` and `TAI_3USD` are better.

**Comment by xlc** [comment]
One issue is that stable asset id 0 on Acala may not be taiKSM. I think we should update `register_stable_asset` to allow specify arbitrary stable asset id and remove `NextStableAssetId`. So that we reserve 0 for taiKSM, 1 for 3USD, 2 for tDOT.

**Comment by zjb0807** [comment]
> One issue is that stable asset id 0 on Acala may not be taiKSM. I think we should update `register_stable_asset` to allow specify arbitrary stable asset id and remove `NextStableAssetId`. So that we reserve 0 for taiKSM, 1 for 3USD, 2 for tDOT.

There is a potential mapping here. If `NextStableAssetId` is deleted, `stable-asset` module needs to be updated.

**Review by xlc — APPROVED** [review]

**Pull request merged**
