### PR TITLE
Migrate storage for substrate version bump

### LINKED ISSUE #1404: Migration for next version of Substrate
After we upgraded to next version of Substrate

Migrations required:
- [ ] https://github.com/paritytech/substrate/pull/9080 https://github.com/paritytech/polkadot/pull/3263
- [ ] https://github.com/paritytech/substrate/pull/9711 https://github.com/paritytech/polkadot/pull/3801
- [ ] https://github.com/paritytech/substrate/pull/9115 https://github.com/paritytech/polkadot/pull/3265
- [ ] https://github.com/paritytech/substrate/pull/9566 https://github.com/paritytech/polkadot/pull/3704
- [x] https://github.com/paritytech/substrate/pull/9796, `Session` is already used in `construct_runtime!` in mandala, acala and karura runtimes, therefore no migration is needed

### PR DESCRIPTION
**Pull request by ferrell-code**
closes #1404

### CODE REVIEW

**Comment by ferrell-code** [comment]
Do we want to run a migration on mandala for any test nets too?

**Comment by ferrell-code** [comment]
Running `target/debug/acala try-runtime --execution wasm --chain karura-dev on-runtime-upgrade live '--uri=wss://karura.api.onfinality.io/public-ws'`
2021-10-18 19:09:59 scraping key-pairs from remote @ 0x52482ba4a6d7392947d06d5fbf38985845826d674fd17b881bfb6e2590c98e04    
2021-10-18 19:09:59 downloading data for all pallets.    
2021-10-18 19:33:51 injecting a total of 229458 keys    
2021-10-18 19:34:55 found matching spec name: "karura"    
2021-10-18 19:34:55 found matching spec version: 1014    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance1Membership' ==> 'GeneralCouncilMembership'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance2Membership' ==> 'FinancialCouncilMembership'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance3Membership' ==> 'HomaCouncilMembership'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance4Membership' ==> 'TechnicalCommitteeMembership'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance5Membership' ==> 'OperatorMembershipAcala'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance1Collective' ==> 'GeneralCouncil'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance2Collective' ==> 'FinancialCouncil'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance3Collective' ==> 'HomaCouncil'    
2021-10-18 19:34:55 pre-migration, prefix: 'Instance4Collective' ==> 'TechnicalCommittee'    
2021-10-18 19:34:55 pre-migration prefix of storage 'Tips': 'Treasury' ==> 'Tips'    
2021-10-18 19:34:55 pre-migration prefix of storage 'Reasons': 'Treasury' ==> 'Tips'    
2021-10-18 19:34:55 pre-migration prefix of storage 'BountyCount': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 pre-migration prefix of storage 'Bounties': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 pre-migration prefix of storage 'BountyDescriptions': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 pre-migration prefix of storage 'BountyApprovals': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 Running migration to v4 for membership with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance1Membership' ==> 'GeneralCouncilMembership'    
2021-10-18 19:34:55 Running migration to v4 for membership with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance2Membership' ==> 'FinancialCouncilMembership'    
2021-10-18 19:34:55 Running migration to v4 for membership with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance3Membership' ==> 'HomaCouncilMembership'    
2021-10-18 19:34:55 Running migration to v4 for membership with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance4Membership' ==> 'TechnicalCommitteeMembership'    
2021-10-18 19:34:55 Running migration to v4 for membership with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance5Membership' ==> 'OperatorMembershipAcala'    
2021-10-18 19:34:55 Running migration to v4 for collective with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance1Collective' ==> 'GeneralCouncil'    
2021-10-18 19:34:55 Running migration to v4 for collective with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance2Collective' ==> 'FinancialCouncil'    
2021-10-18 19:34:55 Running migration to v4 for collective with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance3Collective' ==> 'HomaCouncil'    
2021-10-18 19:34:55 Running migration to v4 for collective with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration, prefix: 'Instance4Collective' ==> 'TechnicalCommittee'    
2021-10-18 19:34:55 Running migration to v4 for tips with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration prefix of storage 'Tips': 'Treasury' ==> 'Tips'    
2021-10-18 19:34:55 migration prefix of storage 'Reasons': 'Treasury' ==> 'Tips'    
2021-10-18 19:34:55 Running migration to v4 for bounties with storage version <wasm:stripped>    
2021-10-18 19:34:55 migration prefix of storage 'BountyCount': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 migration prefix of storage 'Bounties': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 migration prefix of storage 'BountyDescriptions': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 migration prefix of storage 'BountyApprovals': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 ⚠️ System declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-10-18 19:34:55 ✅ no migration for Sudo    
2021-10-18 19:34:55 ✅ no migration for EvmManager    
2021-10-18 19:34:55 ✅ no migration for EvmAccounts    
2021-10-18 19:34:55 ✅ no migration for EVMBridge    
2021-10-18 19:34:55 ✅ no migration for EVM    
2021-10-18 19:34:55 ✅ no migration for NFT    
2021-10-18 19:34:55 ✅ no migration for Incentives    
2021-10-18 19:34:55 ✅ no migration for HomaLite    
2021-10-18 19:34:55 ✅ no migration for EmergencyShutdown    
2021-10-18 19:34:55 ✅ no migration for CdpEngine    
2021-10-18 19:34:55 ✅ no migration for CdpTreasury    
2021-10-18 19:34:55 ✅ no migration for Honzon    
2021-10-18 19:34:55 ✅ no migration for Loans    
2021-10-18 19:34:55 ✅ no migration for AuctionManager    
2021-10-18 19:34:55 ✅ no migration for Dex    
2021-10-18 19:34:55 ✅ no migration for Prices    
2021-10-18 19:34:55 ✅ no migration for OrmlNFT    
2021-10-18 19:34:55 ✅ no migration for Rewards    
2021-10-18 19:34:55 ✅ no migration for Auction    
2021-10-18 19:34:55 ✅ no migration for OperatorMembershipAcala    
2021-10-18 19:34:55 ✅ no migration for AcalaOracle    
2021-10-18 19:34:55 ✅ no migration for Democracy    
2021-10-18 19:34:55 ✅ no migration for TechnicalCommitteeMembership    
2021-10-18 19:34:55 ✅ no migration for TechnicalCommittee    
2021-10-18 19:34:55 ✅ no migration for HomaCouncilMembership    
2021-10-18 19:34:55 ✅ no migration for HomaCouncil    
2021-10-18 19:34:55 ✅ no migration for FinancialCouncilMembership    
2021-10-18 19:34:55 ✅ no migration for FinancialCouncil    
2021-10-18 19:34:55 ✅ no migration for GeneralCouncilMembership    
2021-10-18 19:34:55 ✅ no migration for GeneralCouncil    
2021-10-18 19:34:55 ✅ no migration for Authority    
2021-10-18 19:34:55 ✅ no migration for OrmlXcm    
2021-10-18 19:34:55 ✅ no migration for UnknownTokens    
2021-10-18 19:34:55 ✅ no migration for XTokens    
2021-10-18 19:34:55 ✅ no migration for DmpQueue    
2021-10-18 19:34:55 ✅ no migration for CumulusXcm    
2021-10-18 19:34:55 ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `<wasm:stripped>` vs current storage version `<wasm:stripped>`    
2021-10-18 19:34:55 ✅ no migration for XcmpQueue    
2021-10-18 19:34:55 ✅ no migration for SessionManager    
2021-10-18 19:34:55 ✅ no migration for AuraExt    
2021-10-18 19:34:55 ✅ no migration for Aura    
2021-10-18 19:34:55 ✅ no migration for Session    
2021-10-18 19:34:55 ✅ no migration for CollatorSelection    
2021-10-18 19:34:55 ✅ no migration for Authorship    
2021-10-18 19:34:55 ✅ no migration for ParachainInfo    
2021-10-18 19:34:55 ✅ no migration for ParachainSystem    
2021-10-18 19:34:55 ✅ no migration for Tips    
2021-10-18 19:34:55 ✅ no migration for Bounties    
2021-10-18 19:34:55 ✅ no migration for Treasury    
2021-10-18 19:34:55 ✅ no migration for TransactionPayment    
2021-10-18 19:34:55 ✅ no migration for Vesting    
2021-10-18 19:34:55 ✅ no migration for Currencies    
2021-10-18 19:34:55 ✅ no migration for Tokens    
2021-10-18 19:34:55 ✅ no migration for Balances    
2021-10-18 19:34:55 ✅ no migration for TransactionPause    
2021-10-18 19:34:55 ✅ no migration for Proxy    
2021-10-18 19:34:55 ✅ no migration for Multisig    
2021-10-18 19:34:55 ✅ no migration for Utility    
2021-10-18 19:34:55 ✅ no migration for Scheduler    
2021-10-18 19:34:55 ✅ no migration for Timestamp    
2021-10-18 19:34:55 post-migration, prefix: 'Instance1Membership' ==> 'GeneralCouncilMembership'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance2Membership' ==> 'FinancialCouncilMembership'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance3Membership' ==> 'HomaCouncilMembership'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance4Membership' ==> 'TechnicalCommitteeMembership'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance5Membership' ==> 'OperatorMembershipAcala'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance1Collective' ==> 'GeneralCouncil'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance2Collective' ==> 'FinancialCouncil'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance3Collective' ==> 'HomaCouncil'    
2021-10-18 19:34:55 post-migration, prefix: 'Instance4Collective' ==> 'TechnicalCommittee'    
2021-10-18 19:34:55 post-migration prefix of storage 'Tips': 'Treasury' ==> 'Tips'    
2021-10-18 19:34:55 post-migration prefix of storage 'Reasons': 'Treasury' ==> 'Tips'    
2021-10-18 19:34:55 post-migration prefix of storage 'BountyCount': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 post-migration prefix of storage 'Bounties': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 post-migration prefix of storage 'BountyDescriptions': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 post-migration prefix of storage 'BountyApprovals': 'Treasury' ==> 'Bounties'    
2021-10-18 19:34:55 TryRuntime_on_runtime_upgrade executed without errors. Consumed weight = 5500100000000, total weight = 500000000000 (11.0002)

**Comment by ferrell-code** [comment]
Yeah that doesn't really make sense, the -s snapshot.bin also is just outputting a close to empty file (60 Bytes) which doesn't make sense either, I suspect the client isn't properly working for try-runtime

**Comment by xlc** [comment]
>  the max weight just ensures nothing else is executed until the storage migration is finished
this is just a bad hack

we don't have that many storage items for migrated pallets so it should be safe

**Comment by ferrell-code** [comment]
Yeah I agree the number of keys we are actually migrating is pretty low, but still seems a bit of a foot gun that could blow up in someones face at some point in the future

**Pull request merged**
