### PR TITLE
Benchmark evm

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Comment by ferrell-code** [comment]
fyi, changes to handlebars-rust upstream broke our handlebars templates #1688 will fix

**Review by zjb0807 — APPROVED** [review]

**Review by ferrell-code — APPROVED** [review]
It all looks reasonable to me. We may want to in the future setup an e2e test filling blocks to the maximum block weight on different evm calls and seeing if block production slows/stalls

**Pull request merged**
