### PR TITLE
Integrate chainlink feed

### LINKED ISSUE #1056: Chainlink integration
https://github.com/smartcontractkit/chainlink-polkadot/tree/master/pallet-chainlink-feed

should feed it into orml-oracle somehow

### PR DESCRIPTION
**Pull request by wangjj9219**
close #1056

### CODE REVIEW

**Comment by ferrell-code** [comment]
@wangjj9219 request review, can't actually request review because it is your pr ;).

Reasonable initial integration of the pallet-chainlink-feed for testnet. I would say the chainlink pallet still needs a bit more work on the slashing mechanism for if an oracle is giving bad/malicious feeds.

Adds LINK token (unsupported in karura/acala) and new chainlink types that need to be added to acala.js

**Comment by xlc** [comment]
Should be fine but will take a closer look later. I don't want to merge until Acala genesis is ready.

**Comment by sacha-l** [comment]
What's the status of this PR?

**Comment by xlc** [comment]
It is on hold as waiting the chainlink pallet to be updated to latest Substrate version.

**Pull request closed without merging**
