### PR TITLE
Update Dex Benchmaking

### PR DESCRIPTION
**Pull request by ferrell-code**
Fixes swap benchmarks, I can restore the weights files if we don't want to merge that right now

### CODE REVIEW

**Comment by ferrell-code** [comment]
fn swap_with_exact_supply(u: u32, ) -> Weight {
		(71_776_000 as Weight)
			// Standard Error: 152_000
			.saturating_add((10_256_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().reads((2 as Weight).saturating_mul(u as Weight)))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(u as Weight)))
	}
	fn swap_with_exact_target(u: u32, ) -> Weight {
		(72_164_000 as Weight)
			// Standard Error: 252_000
			.saturating_add((9_648_000 as Weight).saturating_mul(u as Weight))
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().reads((2 as Weight).saturating_mul(u as Weight)))
			.saturating_add(T::DbWeight::get().writes(2 as Weight))
			.saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(u as Weight)))
	}

**Comment by ferrell-code** [comment]
Locally I get that output, but the benchbot doesn't generate the same reads and write scheme, obviously the numbers are different but shouldn't the reads and writes be identical across machines?

**Review by xlc — APPROVED** [review]
the weight changes looks reasonable

**Review by ermalkaleci — APPROVED** [review]
LGTM

**Pull request merged**
