### PR TITLE
improved build release script

### LINKED ISSUE #1722: Improve release build process
Current process: https://github.com/AcalaNetwork/Acala/blob/master/.github/workflows/release-notes.yml

We want something more automated and easier to manage.

### PR DESCRIPTION
**Pull request by syan095**
Improved script to build release WASM and publishing them.

Closes #1722

### CODE REVIEW

**Comment by syan095** [comment]
I created a fork to test this script:
https://github.com/syan095/Acala/actions/workflows/publish-release.yml

**Comment by zjb0807** [comment]
Please remove `release-notes.yml`

**Comment by ermalkaleci** [comment]
I had to run srtool step manually to get the expected output, I don't think this will work. I guess rest is the same, right?

**Comment by syan095** [comment]
> I had to run srtool step manually to get the expected output, I don't think this will work. I guess rest is the same, right?

Yeah on my fork the script ran all the way to Pinata upload without problem. I think the new github action for srtool takes care of all the setups

**Pull request merged**
