### PR TITLE
karura benchmarks

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Comment by xlc** [comment]
add some comments on duplicated files and more comments on changed lines so we can merge them easier in future.

**Comment by ermalkaleci** [comment]
> add some comments on duplicated files and more comments on changed lines so we can merge them easier in future.

@xlc code remains the same, the only change is currency_id e.g: `KAR` instead of `ACA`

**Comment by ermalkaleci** [comment]
/bench runtime custom --chain=karura-latest --steps=50 --repeat=20 --pallet=* --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./HEADER-GPL3 --output=./runtime/karura/src/weights/

**Comment by ermalkaleci** [comment]
/bench runtime custom --chain=karura-latest --steps=50 --repeat=20 --pallet=* --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./HEADER-GPL3 --output=./runtime/karura/src/weights/

**Comment by ermalkaleci** [comment]
/bench runtime custom --chain=karura-latest --steps=50 --repeat=20 --pallet="*" --extrinsic="*" --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./HEADER-GPL3 --output=./runtime/karura/src/weights/

**Comment by ermalkaleci** [comment]
/bench runtime custom --chain=karura-latest --steps=50 --repeat=20 --pallet=* --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./HEADER-GPL3 --output=./runtime/karura/src/weights/

**Comment by xlc** [comment]
> > add some comments on duplicated files and more comments on changed lines so we can merge them easier in future.
> 
> @xlc code remains the same, the only change is currency_id e.g: `KAR` instead of `ACA`

Can you add comment on top of duplicated file to indicate where it is coming from?

**Comment by ermalkaleci** [comment]
/bench runtime custom --chain=karura-latest --steps=50 --repeat=20 --pallet=* --extrinsic=* --execution=wasm --wasm-execution=compiled --heap-pages=4096 --header=./HEADER-GPL3 --output=./runtime/karura/src/weights/

**Pull request merged**
