### PR TITLE
Update ecrecover precompile

### PR DESCRIPTION
**Pull request by zjb0807**
ref: https://github.com/polkadot-evm/frontier/pull/964

### CODE REVIEW

**Comment by ermalkaleci** [comment]
we already have the correct version, what does this change?

**Comment by zjb0807** [comment]
@ermalkaleci 

https://github.com/AcalaNetwork/Acala/blob/0b8c9b4b174401214f8ab4465bffaaa497527db9/modules/evm/src/precompiles/ecrecover.rs#L42-L47

If v > 26, then sig[64] = v - 27, let it be 0 or 1.  
while geth version only accept 27 and 28.

**Comment by ermalkaleci** [comment]
That's all we need

**Comment by ermalkaleci** [comment]
if this is fixing an issue then there should be a test. where's `v - 27` https://github.com/ethereum/go-ethereum/blob/a907d7e81aaeea15d80b2d3209ad8e08e3bf49e0/core/vm/contracts.go#L174?

**Comment by zjb0807** [comment]
It checked that `input[63] > 26`, so if it is `input[63] = 30`, it need to continue to verify the signature.
Now strictly check input[63] is 27/28.

**Comment by ermalkaleci** [comment]
> It checked that `input[63] > 26`, so if it is `input[63] = 30`, it need to continue to verify the signature.
> 
> Now strictly check input[63] is 27/28.

If v > 26 then v - 27

**Comment by zjb0807** [comment]
> If v > 26 then v - 27

So v can be `27~255` to call `secp256k1_ecdsa_recover`. Now it is only allowed on 27/28.

**Pull request merged**
