### PR TITLE
add dev container

### LINKED ISSUE #1185: support devcontainer
https://code.visualstudio.com/docs/remote/containers

useful for quickly setup dev env as well as use remote docker instance to build & run

### PR DESCRIPTION
**Pull request by ferrell-code**
fixes #1185 

adds devcontainer, took a generic devcontainer template for rust I think the settings look reasonable :palm_tree: 

Edit: I believe CI is complaining about something unrelated to the pr

### CODE REVIEW

**Comment by xlc** [comment]
Thanks for the PR. Will give it a try.

**Comment by xlc** [comment]
Doesn't work for me using remote context

```
[2021-07-25T23:44:38.769Z] Remote-Containers 0.187.1 in VS Code 1.58.2 (c3f126316369cd610563c75b1b1725e0679adfb3).
[2021-07-25T23:44:38.769Z] Start: Resolving Remote
[2021-07-25T23:44:38.773Z] Setting up container for folder or workspace: /Users/xiliangchen/projects/acala/acala
[2021-07-25T23:44:38.774Z] Context: office
[2021-07-25T23:44:38.776Z] Start: Check Docker is running
[2021-07-25T23:44:38.777Z] Start: Run: docker version --format {{.Server.APIVersion}}
[2021-07-25T23:44:39.138Z] Stop (361 ms): Run: docker version --format {{.Server.APIVersion}}
[2021-07-25T23:44:39.138Z] Server API version: 1.41
[2021-07-25T23:44:39.139Z] Stop (363 ms): Check Docker is running
[2021-07-25T23:44:39.148Z] Start: Run: git rev-parse --show-cdup
[2021-07-25T23:44:39.153Z] Stop (5 ms): Run: git rev-parse --show-cdup
[2021-07-25T23:44:39.154Z] Start: Run: docker ps -q -a --filter label=vsch.local.folder=/Users/xiliangchen/projects/acala/acala --filter label=vsch.quality=stable
[2021-07-25T23:44:39.424Z] Stop (270 ms): Run: docker ps -q -a --filter label=vsch.local.folder=/Users/xiliangchen/projects/acala/acala --filter label=vsch.quality=stable
[2021-07-25T23:44:39.427Z] Start: Run: docker build -f /Users/xiliangchen/projects/acala/acala/scripts/Dockerfile -t vsc-acala-25176ed06f7dca867b850a736e65bb76 /Users/xiliangchen/projects/acala/acala/scripts
[2021-07-25T23:44:40.370Z] Sending build context to Docker daemon  16.38kB

[2021-07-25T23:44:40.437Z] Step 1/35 : FROM rust as planner
[2021-07-25T23:44:40.438Z]  ---> 61281569db97
Step 2/35 : WORKDIR app
[2021-07-25T23:44:40.439Z]  ---> Using cache
 ---> e5d00cdadc8a
Step 3/35 : RUN rustup default nightly-2021-06-01
[2021-07-25T23:44:40.440Z]  ---> Using cache
 ---> 1ef4bf6bd5ab
[2021-07-25T23:44:40.440Z] Step 4/35 : RUN cargo install cargo-chef
 ---> Using cache
 ---> f063db1f252b
Step 5/35 : COPY . .
 ---> Using cache
 ---> 6ead32aed5b9
Step 6/35 : RUN cargo chef prepare  --recipe-path recipe.json
 ---> Using cache
 ---> 72106f10d2ca
Step 7/35 : FROM rust as cacher
 ---> 61281569db97
Step 8/35 : WORKDIR app
 ---> Using cache
 ---> e5d00cdadc8a
Step 9/35 : RUN rustup default nightly-2021-06-01 && 	rustup target add wasm32-unknown-unknown --toolchain nightly-2021-06-01
[2021-07-25T23:44:40.441Z]  ---> Using cache
 ---> 99fb2ff0b84c
Step 10/35 : RUN cargo install cargo-chef
[2021-07-25T23:44:40.443Z]  ---> Using cache
 ---> 5623a54ad723
Step 11/35 : RUN apt-get update && 	apt-get dist-upgrade -y -o Dpkg::Options::="--force-confold" && 	apt-get install -y cmake pkg-config libssl-dev git clang libclang-dev
 ---> Using cache
 ---> 28850fe39d54
Step 12/35 : COPY --from=planner /app/recipe.json recipe.json
 ---> Using cache
[2021-07-25T23:44:40.469Z]  ---> 3f4644d5ff42
Step 13/35 : RUN cargo chef cook --recipe-path recipe.json --release
[2021-07-25T23:44:40.549Z]  ---> Running in 03f13f3898fb
[2021-07-25T23:44:40.924Z] error: could not find `Cargo.toml` in `/app` or any parent directory
thread 'main' panicked at 'Exited with status code: 101', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cargo-chef-0.1.21/src/recipe.rs:136:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-07-25T23:44:41.181Z] The command '/bin/sh -c cargo chef cook --recipe-path recipe.json --release' returned a non-zero code: 101
[2021-07-25T23:44:41.186Z] Stop (1759 ms): Run: docker build -f /Users/xiliangchen/projects/acala/acala/scripts/Dockerfile -t vsc-acala-25176ed06f7dca867b850a736e65bb76 /Users/xiliangchen/projects/acala/acala/scripts
[2021-07-25T23:44:41.191Z] Command failed: docker build -f /Users/xiliangchen/projects/acala/acala/scripts/Dockerfile -t vsc-acala-25176ed06f7dca867b850a736e65bb76 /Users/xiliangchen/projects/acala/acala/scripts
```

Should be something similar to this https://github.com/substrate-developer-hub/substrate-node-template/blob/master/.devcontainer/devcontainer.json

**Comment by ferrell-code** [comment]
ah yes, I added context field and that fixes that particular issue... I will let it build fully and let you know

**Comment by xlc** [comment]
Not sure if we want to reuse the Dockerfile for prod image build for development as well. Maybe a standard Debian based Rust image is preferable for development purpose.

**Comment by ferrell-code** [comment]
yeah that makes more sense, made the image real simple. I'll let it compile and test it out :+1:

**Comment by xlc** [comment]
Screen Shot 2021-07-28 at 11 59 26 AM

I think something isn't configured correctly.

**Comment by ferrell-code** [comment]
[
Screenshot from 2021-07-27 21-59-03
That's strange it looks like this on my machine... hmmm

**Comment by xlc** [comment]
I am using remote docker context so that could be just VSCode issue. Will try local one.

**Comment by xlc** [comment]
Looks like it is VSCode extension cannot handle remote docker context which makes this less useful, but still a nice feature. Thanks for the PR!

**Comment by ferrell-code** [comment]
Unfortunate, were you trying use a cloud service for really fast builds cause I have thought about that when I'm waiting like an hour for it to compile lol

**Comment by xlc** [comment]
Yeah my MacBook is unusable when dealing with Rust projects. So we have setup a powerful machine in our office and few some cloud build servers. I always use those remote machine to compile Rust projects.

**Pull request merged**
