### PR TITLE
aggregated storage logs

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Review by zjb0807 — COMMENTED** [review]
We can combine the vector here for easier debugging
https://github.com/AcalaNetwork/Acala/blob/39d92de340bf9bfa560346eea68abdb556b7b45b/modules/evm/src/runner/stack.rs#L141-L156

**Comment by ermalkaleci** [comment]
@zjb0807 not sure what you mean. can you give an example?

**Review by xlc — DISMISSED** [review]

**Comment by xlc** [comment]
some test will be good

**Review by xlc — DISMISSED** [review]

**Comment by zjb0807** [comment]
```
diff --git a/modules/evm/src/runner/stack.rs b/modules/evm/src/runner/stack.rs
index 8b6c5d6b..0bdc1bef 100644
--- a/modules/evm/src/runner/stack.rs
+++ b/modules/evm/src/runner/stack.rs
@@ -138,7 +138,17 @@ impl<T: Config> Runner<T> {
                        state.substate.storage_logs
                );
                let mut sum_storage: i32 = 0;
-               for (target, storage) in &state.substate.storage_logs {
+               for (target, storage) in
+                       &state
+                               .substate
+                               .storage_logs
+                               .iter()
+                               .fold(BTreeMap::<H160, i32>::new(), |mut bmap, (target, storage)| {
+                                       bmap.entry(*target)
+                                               .and_modify(|x| *x = x.saturating_add(*storage))
+                                               .or_insert(*storage);
+                                       bmap
+                               }) {
                        if !skip_storage_rent {
                                Pallet::<T>::charge_storage(&origin, target, *storage).map_err(|e| {
                                        log::debug!(
```

How about this? Merge the storage logs, then do `charge_storage`, we can log and debug it easier.

**Comment by ermalkaleci** [comment]
@zjb0807 Yes this works as well. This was my first idea but in my head it was better to debug if they're aggregated by target rather than multiple addresses with chunk storage log. I am letting you guys decide @xlc

**Comment by xlc** [comment]
I think @zjb0807 's method is slightly more efficient and yeah helps with debugging so let's do that

**Review by zjb0807 — APPROVED** [review]
Awaiting audit

**Pull request merged**
