### PR TITLE
Homa-lite: use 'Any' network id for sovereign sub-account.

### LINKED ISSUE #1324: Change homa-lite relay chain NetworkId in runtime config to Any
There is no point to set a specific network id in our case. `Any` works both in production and rococo testing env.

### PR DESCRIPTION
**Pull request by shaunxw**
Closes #1324

### CODE REVIEW

**Comment by syan095** [comment]
I think you may need to update the parachain_subaccounts_are_unique test as well

**Comment by xlc** [comment]
Already confirmed this won't break anything?

**Comment by shaunxw** [comment]
> I think you may need to update the parachain_subaccounts_are_unique test as well

This test is only for Mandala runtime and there in no change there.

**Comment by shaunxw** [comment]
> Already confirmed this won't break anything?

Only network id of homa-lite sovereign subaccount location is changed. The relay chain network id for xcm related types and configs is not touched, so there is no breaks.

**Review by syan095 — APPROVED** [review]

**Review by xlc — APPROVED** [review]

**Pull request merged**
