### PR TITLE
add option to pause evm precompiles

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Review by zjb0807 — COMMENTED** [review]
LGTM.
Do we need to suspend the functionality of the contract addresses that has loophole?

**Comment by ermalkaleci** [comment]
> LGTM.
> 
> Do we need to suspend the functionality of the contract addresses that has loophole?

I don't think we should. If the team wants to pause something they can add the feature into their contract

**Review by xlc — APPROVED** [review]

**Pull request merged**
