### PR TITLE
Remove TransactionPayment from  construct_runtime

### PR DESCRIPTION
**Pull request by HZHAIX**
PR for #433

### CODE REVIEW

**Comment by xlc** [comment]
I wish this is easy as it is... but it is not. You will need to ensure the transaction payment RPC still works and everything still compiles.

**Review by xlc — CHANGES_REQUESTED** [review]
I wish this is easy as it is... but it is not. You will need to ensure the transaction payment RPC still works and everything still compiles.

**Comment by HZHAIX** [comment]
@xlc Is is ok to add `query_info` function in `module_account` ?

**Comment by xlc** [comment]
This will make RPC not working.

This needs to be removed.
https://github.com/AcalaNetwork/Acala/blob/7135e5828a92899be03598226cd48a428ecff93d/runtime/dev/src/lib.rs#L293-L299

`query_info` needs to be implemented within `module-accounts`

**Pull request closed without merging**
